[build-system]
requires = ["setuptools", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "l2f"
version = "0.0.1"
description = "Python bindings for the L2F (Learning to Fly) Simulator"
authors = [
    { name = "Jonas Eschmann", email = "jonas.eschmann@gmail.com" }
]

